 GGeURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Array Blogs'
theme = "terminal"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/lxde"

[Languages.en-gb.params.author]
  #avatar = "avatar.jpg"
  intro = "Array's Blog"
  name = "Zac P"
  description = "I like linux"
